//
// Created by simon on 07.01.23.
//

#ifndef AUTHORIZATION_MANAGEMENT_PERMISSIONPROVIDERSERVICE_H
#define AUTHORIZATION_MANAGEMENT_PERMISSIONPROVIDERSERVICE_H


class PermissionProviderService {

};


#endif //AUTHORIZATION_MANAGEMENT_PERMISSIONPROVIDERSERVICE_H
