version: '3.9'

services:
  keycloak:
    build:
      context: .
      dockerfile: keycloak.Dockerfile
    environment:
      KC_HOSTNAME_STRICT: false
      KC_PROXY: edge
    env_file:
      - db.env
      - .env
    depends_on:
      - postgres
    networks:
      - keycloak
    ports:
      - "127.0.0.1:8080:8080"

  postgres:
    image: postgres:14.3-alpine
    container_name: keycloak_postgres
    networks:
      - keycloak
    environment:
      PGDATA: /var/lib/postgresql/data
    env_file:
      - db.env


networks:
  keycloak: