version: '3.10'

services:
  auth-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:8000:8000"
    networks:
      - keycloak-external
      - auth-management
    depends_on:
      database:
        condition: service_healthy
    environment:
      - "DATABASE_CONNECTION=postgresql://test_user:test_pw@postgres:5432/test_db"
      - "KEYCLOAK_HOST=keycloak"

  database:
    container_name: postgres
    image: postgres:latest
    restart: always
    networks:
      - auth-management
    environment:
      POSTGRES_PASSWORD: test_pw
      POSTGRES_USER: test_user
      POSTGRES_DB: test_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test_user"]
      interval: 1s
      timeout: 5s
      retries: 5

networks:
  auth-management:
  keycloak-external:
    external: true