//
// Created by simon on 07.01.23.
//

#ifndef AUTHORIZATION_MANAGEMENT_CONFIGPAIRREQUEST_H
#define AUTHORIZATION_MANAGEMENT_CONFIGPAIRREQUEST_H


class ConfigPairRequest {

};


#endif //AUTHORIZATION_MANAGEMENT_CONFIGPAIRREQUEST_H
