//
// Created by simon on 02.01.23.
//

#ifndef AUTHORIZATION_MANAGEMENT_PERMISSIONPROVIDERTYPE_H
#define AUTHORIZATION_MANAGEMENT_PERMISSIONPROVIDERTYPE_H


class PermissionProviderType {

};


#endif //AUTHORIZATION_MANAGEMENT_PERMISSIONPROVIDERTYPE_H
