//
// Created by simon on 02.01.23.
//

#ifndef AUTHORIZATION_MANAGEMENT_PERMISSIONPROVIDER_H
#define AUTHORIZATION_MANAGEMENT_PERMISSIONPROVIDER_H


class PermissionProvider {

};


#endif //AUTHORIZATION_MANAGEMENT_PERMISSIONPROVIDER_H
