//
// Created by simon on 07.01.23.
//

#ifndef AUTHORIZATION_MANAGEMENT_PERMISSIONPROVIDERREQUEST_H
#define AUTHORIZATION_MANAGEMENT_PERMISSIONPROVIDERREQUEST_H


class PermissionProviderRequest {

};


#endif //AUTHORIZATION_MANAGEMENT_PERMISSIONPROVIDERREQUEST_H
