//
// Created by simon on 02.01.23.
//

#ifndef AUTHORIZATION_MANAGEMENT_PERMISSIONREQUEST_H
#define AUTHORIZATION_MANAGEMENT_PERMISSIONREQUEST_H


class PermissionRequest {

};


#endif //AUTHORIZATION_MANAGEMENT_PERMISSIONREQUEST_H
