//
// Created by simon on 07.01.23.
//

#ifndef AUTHORIZATION_MANAGEMENT_PERMISSIONREQUESTDB_H
#define AUTHORIZATION_MANAGEMENT_PERMISSIONREQUESTDB_H

#endif //AUTHORIZATION_MANAGEMENT_PERMISSIONREQUESTDB_H
