//
// Created by simon on 05.01.23.
//

#ifndef AUTHORIZATION_MANAGEMENT_PERMISSIONPROVIDERCONTROLLER_H
#define AUTHORIZATION_MANAGEMENT_PERMISSIONPROVIDERCONTROLLER_H

#endif //AUTHORIZATION_MANAGEMENT_PERMISSIONPROVIDERCONTROLLER_H
